[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
lazy_static = "1.5.0"
rstest = "0.23.0"
sorted-vec = "0.8.5"
regex = "1.11.1"
tailcall = "1.0.1"
